//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment_Management_Application.BAC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeProject
    {
        public int RegistrationID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string ProjectNumber { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
